# docker config for srs.
listen              1935;
max_connections     1000;
srs_log_tank        console;
daemon              off;

http_api {
    enabled         on;
    listen          1985;
}

http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}

vhost __defaultVhost__ {
    hls {
        enabled         on;
        hls_path        ./objs/nginx/html;
        hls_fragment    2;
        hls_window      10;
        hls_cleanup     on;
    }

    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }

    dvr {
        enabled         on;
        dvr_path        ./objs/nginx/html/record/[app]/[stream]/[2006]-[01]-[02]/[stream].[timestamp].mp4;
        dvr_plan        segment;
        dvr_duration    1800;
        dvr_wait_keyframe off;
    }

    http_hooks {
        enabled         on;
        on_publish      http://172.18.0.1:3002/api/srs/webhook/on-publish;
        on_unpublish    http://172.18.0.1:3002/api/srs/webhook/on-unpublish;
        on_dvr          http://172.18.0.1:3002/api/srs/webhook/on-dvr;
    }
}
