version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: newcam-postgres
    environment:
      POSTGRES_DB: newcam
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - newcam-network
    restart: unless-stopped

  # Redis for caching
  redis:
    image: redis:7-alpine
    container_name: newcam-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - newcam-network
    restart: unless-stopped

  # ZLMediaKit - Media Server
  zlmediakit:
    image: zlmediakit/zlmediakit:master
    container_name: newcam-zlmediakit
    ports:
      - "1935:1935"   # RTMP
      - "8080:8080"   # HTTP API
      - "10000-10100:10000-10100/udp"  # RTP
    volumes:
      - ./storage/streams:/opt/media/bin/www/live
      - ./storage/recordings:/opt/media/bin/www/record
      - ./docker/zlmediakit/config.ini:/opt/media-server/conf/config.ini
    environment:
      - TZ=America/Sao_Paulo
    networks:
      - newcam-network
    restart: unless-stopped

  # SRS Server - Alternative streaming
  srs:
    image: ossrs/srs:5
    container_name: newcam-srs
    ports:
      - "1936:1935"   # RTMP (alternative)
      - "8081:8080"   # HTTP API
      - "1985:1985"   # HTTP API
    volumes:
      - srs_data:/usr/local/srs/objs/nginx/html
    environment:
      - TZ=America/Sao_Paulo
    networks:
      - newcam-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  srs_data:

networks:
  newcam-network:
    driver: bridge